name: java-yaml-eureka-client-configs
filetype: (yaml$|yml$)
target: contents
type: yamlpath
criticality: Info
advice: The application is using eureka and setting the connection string
category: eureka
effort: 0
tags:
  - value: eureka
patterns:
  - value: $.eureka.client["service-url","serviceUrl"]