name: java-yaml-config-client-configs
filetype: (yaml$|yml$)
target: contents
type: yamlpath
criticality: Info
advice: The application is using spring config server and setting the connection string
category: config server
effort: 0
tags:
  - value: config server
patterns:
  - value: $.spring.config.import
  - value: $.spring.cloud.config.uri

 # refer to https://docs.spring.io/spring-cloud-config/docs/4.0.0-RC2/reference/html/#_spring_cloud_config_client