name: java-properties-eureka-client-configs
filetype: properties$
target: line
type: regex
#criticality: Info
advice: The application is using eureka and setting the connection string
category: eureka
effort: 0
criticality:
  cloud_native_readiness : 50
  container_readiness: 50
tags:
  - value: eureka
patterns:
  - value: (^|\s)eureka\.client\.(service-url|serviceUrl)