name: config-dotnet-webConfig
filetype: config$
target: file
category: Config
type: simple-text
advice: Upgrade to .Net Core
effort: 0
readiness: 0
criticality:
  cloud_native_readiness : 50
  container_readiness: 50
tags:
- value: web-config
patterns:
- value: web.config
- value: Web.config
profiles:
- value: cloud-suitability