#qc1
name: dotnet-ISAPI-Filters-config
filetype: config$
target: file
type: xpath
advice: Refer to platform documentation
category: unsupported-iis-module
effort: 1000
readiness: 0
criticality: 50:50
patterns:
- value: /configuration/system.webServer/isapiFilters[1]
#- <configuration><system.webServer><isapiFilters
tags:
- value: iis-module
# Mostly a challenge if moving to .NetCore