name: dotnet-windows-code-access-security
filetype: (cs$|vb$)
target: line
type: regex
defaultpattern: .*%s.*
advice: unsupported
patterns:
- value: CodeAccessPermission
readiness: 9
effort: 10
criticality: 10:90
category: security
tags:
- value: security
#-  public class   NameIdPermission : CodeAccessPermission, IUnres