name: dotnet-windows-application-domain
filetype: (cs$|vb$)
target: line
type: regex
defaultpattern: .*%s.*
advice: Unsupported, For .NET Core, there is exactly one AppDomain. Isolation and unloading are provided through AssemblyLoadContext. Security boundaries should be provided by process boundaries and appropriate remoting techniques
patterns:
- value: AppDomain.CreateDomain
readiness: 9
effort: 1000
criticality:
  cloud_native_readiness : 50
  container_readiness: 50
category: windows-domain
tags:
- value: app-domain
- value: security
- value: unsupported-netcore
#- AppDomain newDomain = AppDomain.CreateDomain("newDomain", evidence, setup);
profiles:
- value: cloud-suitability