name: java-system-config
filetype: $
target: line
type: regex
defaultpattern: (System.)%s\(
advice: Review usage of environment variables and system properties and externalize.
effort: 3
readiness: 10 
criticality:
  cloud_native_readiness : 50
  container_readiness: 50
category: config
tags:
- value: config
patterns:
- value: getenv
- value: getProperty
- value: setProperty
- value: setProperties
profiles:
- value: cloud-suitability