name: tas-environment-connector-python
filetype: py$
target: line
type: regex
defaultpattern: ^.*%s
advice: Application appears to be using Cloudfoundry python client to inject environment variables provided by TAS.
effort: 1
readiness: 7
criticality:
  cloud_native_readiness : 50
  container_readiness: 50
category: tas
tags:
  - value: tas
  - value: env-config
patterns:
  - value: CloudFoundryClient
profiles:
- value: tas