#SW
name: xml-transportSecurity
filetype: xml$
target: line
type: regex
defaultpattern: (%s)
category: security
advice: Application Server coupling
effort: 2
readiness: 10
tags:
- value: security
- value: web-app
patterns:
- value: <transport-guarantee>CONFIDENTIAL
##<transport-guarantee>CONFIDENTIAL
