name: dotnet-stack-security
filetype: (cs$|vb$)
target: line
type: regex
defaultpattern: .*%s.*
advice: This is a stack component
effort: 1
readiness: 0
category: security
tags:
- value: stack
patterns:
- value: Microsoft.AspNet.Identity.Owin
- value: Microsoft.IdentityModel.Tokens
- value: System.IdentityModel.Tokens
- value: System.Net.Security
- value: System.Security.Claims
- value: System.Security.Cryptography
- value: System.Web.Security
profiles:
- value: stack